[versions]
loom = "1.7.+"

mc = "1.21"
fl = "0.15.11"
yarn = "1.21+build.9"
fapi = "0.100.7+1.21"

placeholder = "2.4.0+1.21"
polydex = "1.2.2+1.21"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }

placeholder = { group = "eu.pb4", name = "placeholder-api", version.ref = "placeholder" }
polydex = { group = "eu.pb4", name = "polydex", version.ref = "polydex" }