modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
displayURL = "${homepage}"
logoFile = "assets/glowcase/icon.png"
authors = "${members}"
description = '''${modDescription}'''

[[mixins]]
config = "glowcase.mixins.json"

[properties]
"connector:placeholder"=true

[[dependencies.${ modId }]]
modId = "connector"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${mc},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "fabric_api"
type = "required"
versionRange = "[${fapi},)"
ordering = "NONE"
side = "BOTH"
